### ISSUE TITLE
Should not call localStorage.clear as that wipes data for other extensions

### ISSUE THREAD

**Issue by studgeek** [michaeldrotar/Better-Cupid#2]
The code should be updated not to call localStorage.clear() as that wipes storage for all injected content scripts. See https://github.com/benjaffe/chrome-okc-plugin/issues/87. Thanks!

Line that is causing the problem is https://github.com/michaeldrotar/Better-Cupid/blob/59abf79ec64c28bb9ce2bc306c1da2dc98a70de0/libs/core.js#L103

**Comment by michaeldrotar** [comment]
Sorry for the entirely too late reply, guys. This issue is now fixed in v0.8.0, which switches over to using the sync storage. Awesome extension, Ben.

**Comment by benjaffe** [comment]
*sigh of relief*  I was thinking about overloading localStorage.clear() to leave my keys alone, but it seemed so heinous that I procrastinated on doing it. :)

Great to see your repo active again!

**Comment by michaeldrotar** [comment]
Ha, yeah, that would've been painful :) When I started the project, I assumed localstorage was, ya know, local to my extension. What a fool I was...
I'm happy to be back!
